// Mock Users for authentication
export const mockUsers = {
  admin: {
    id: 1,
    name: 'Admin User',
    email: 'admin@mindspire.com',
    role: 'admin',
    avatar: 'https://bit.ly/sage-adebayo',
  },
  teacher: {
    id: 2,
    name: 'Teacher Ali',
    email: 'teacher@mindspire.com',
    role: 'teacher',
    avatar: 'https://bit.ly/ryan-florence',
  },
  student: {
    id: 3,
    name: 'Student Ahmed',
    email: 'student@mindspire.com',
    role: 'student',
    avatar: 'https://bit.ly/prosper-baba',
  },
  driver: {
    id: 4,
    name: 'Driver Umar',
    email: 'driver@mindspire.com',
    role: 'driver',
    avatar: 'https://bit.ly/dan-abramov',
  },
};

// Mock Statistics for Dashboard
export const mockStats = {
  totalStudents: 1250,
  totalTeachers: 85,
  activeBuses: 12,
  todayAttendance: 92,
};

// Mock Bus Data with Telematics
export const mockBuses = [
  {
    id: 1,
    busNumber: 'BUS-001',
    driverName: 'John Smith',
    driverPhone: '+1234567890',
    lat: 40.7128,
    lng: -74.0060,
    speed: 35,
    heading: 'North',
    studentCount: 25,
    maxCapacity: 40,
    ignition: true,
    fuelLevel: 85,
    temperature: 22,
    status: 'active',
    route: 'Route A - Downtown',
    nextStop: 'Main Street',
    eta: '10 mins',
  },
  {
    id: 2,
    busNumber: 'BUS-002',
    driverName: 'Maria Garcia',
    driverPhone: '+1234567891',
    lat: 40.7260,
    lng: -73.9897,
    speed: 28,
    heading: 'South',
    studentCount: 30,
    maxCapacity: 40,
    ignition: true,
    fuelLevel: 70,
    temperature: 23,
    status: 'active',
    route: 'Route B - Uptown',
    nextStop: 'Park Avenue',
    eta: '15 mins',
  },
  {
    id: 3,
    busNumber: 'BUS-003',
    driverName: 'Ahmed Khan',
    driverPhone: '+1234567892',
    lat: 40.7489,
    lng: -73.9680,
    speed: 0,
    heading: 'East',
    studentCount: 0,
    maxCapacity: 40,
    ignition: false,
    fuelLevel: 95,
    temperature: 21,
    status: 'inactive',
    route: 'Route C - Suburbs',
    nextStop: 'School Parking',
    eta: 'Parked',
  },
  {
    id: 4,
    busNumber: 'BUS-004',
    driverName: 'Linda Johnson',
    driverPhone: '+1234567893',
    lat: 40.7589,
    lng: -73.9851,
    speed: 42,
    heading: 'West',
    studentCount: 18,
    maxCapacity: 40,
    ignition: true,
    fuelLevel: 60,
    temperature: 24,
    status: 'active',
    route: 'Route D - Highway',
    nextStop: 'Exit 12',
    eta: '8 mins',
  },
];

// Mock RFID Attendance Logs
export const mockAttendanceLogs = [
  {
    id: 1,
    timestamp: '08:15:23 AM',
    studentName: 'Alice Johnson',
    studentId: 'STU001',
    rfidTag: 'RFID-001',
    busNumber: 'BUS-001',
    status: 'Boarding',
    location: 'Main Gate',
  },
  {
    id: 2,
    timestamp: '08:14:45 AM',
    studentName: 'Bob Smith',
    studentId: 'STU002',
    rfidTag: 'RFID-002',
    busNumber: 'BUS-001',
    status: 'Boarding',
    location: 'Main Gate',
  },
  {
    id: 3,
    timestamp: '08:13:12 AM',
    studentName: 'Charlie Brown',
    studentId: 'STU003',
    rfidTag: 'RFID-003',
    busNumber: 'BUS-002',
    status: 'Boarding',
    location: 'North Gate',
  },
  {
    id: 4,
    timestamp: '08:12:30 AM',
    studentName: 'Diana Prince',
    studentId: 'STU004',
    rfidTag: 'RFID-004',
    busNumber: 'BUS-002',
    status: 'Boarding',
    location: 'North Gate',
  },
  {
    id: 5,
    timestamp: '08:10:45 AM',
    studentName: 'Eva Martinez',
    studentId: 'STU005',
    rfidTag: 'RFID-005',
    busNumber: 'BUS-001',
    status: 'Boarding',
    location: 'Main Gate',
  },
];

// Mock Student Data
export const mockStudents = [
  {
    id: 1,
    name: 'Alice Johnson',
    rollNumber: 'STU001',
    class: '10',
    section: 'A',
    rfidTag: 'RFID-001',
    busNumber: 'BUS-001',
    attendance: 95,
    feeStatus: 'paid',
    parentName: 'Robert Johnson',
    parentPhone: '+1234567894',
    email: 'alice.j@school.com',
    avatar: 'https://bit.ly/dan-abramov',
  },
  {
    id: 2,
    name: 'Bob Smith',
    rollNumber: 'STU002',
    class: '10',
    section: 'B',
    rfidTag: 'RFID-002',
    busNumber: 'BUS-001',
    attendance: 88,
    feeStatus: 'pending',
    parentName: 'Mary Smith',
    parentPhone: '+1234567895',
    email: 'bob.s@school.com',
    avatar: 'https://bit.ly/kent-c-dodds',
  },
  {
    id: 3,
    name: 'Charlie Brown',
    rollNumber: 'STU003',
    class: '9',
    section: 'A',
    rfidTag: 'RFID-003',
    busNumber: 'BUS-002',
    attendance: 92,
    feeStatus: 'paid',
    parentName: 'David Brown',
    parentPhone: '+1234567896',
    email: 'charlie.b@school.com',
    avatar: 'https://bit.ly/code-beast',
  },
  {
    id: 4,
    name: 'Diana Prince',
    rollNumber: 'STU004',
    class: '9',
    section: 'B',
    rfidTag: 'RFID-004',
    busNumber: 'BUS-002',
    attendance: 78,
    feeStatus: 'overdue',
    parentName: 'Steve Prince',
    parentPhone: '+1234567897',
    email: 'diana.p@school.com',
    avatar: 'https://bit.ly/sage-adebayo',
  },
  {
    id: 5,
    name: 'Eva Martinez',
    rollNumber: 'STU005',
    class: '11',
    section: 'A',
    rfidTag: 'RFID-005',
    busNumber: 'BUS-001',
    attendance: 96,
    feeStatus: 'paid',
    parentName: 'Carlos Martinez',
    parentPhone: '+1234567898',
    email: 'eva.m@school.com',
    avatar: 'https://bit.ly/prosper-baba',
  },
];

// Mock Teacher Data
export const mockTeachers = [
  {
    id: 1,
    name: 'Dr. Sarah Wilson',
    employeeId: 'TCH001',
    subject: 'Mathematics',
    classes: ['10A', '10B', '11A'],
    phone: '+1234567899',
    email: 'sarah.w@school.com',
    avatar: 'https://bit.ly/sage-adebayo',
    experience: '10 years',
  },
  {
    id: 2,
    name: 'Prof. James Anderson',
    employeeId: 'TCH002',
    subject: 'Physics',
    classes: ['11A', '11B', '12A'],
    phone: '+1234567900',
    email: 'james.a@school.com',
    avatar: 'https://bit.ly/ryan-florence',
    experience: '15 years',
  },
  {
    id: 3,
    name: 'Ms. Emily Davis',
    employeeId: 'TCH003',
    subject: 'English',
    classes: ['9A', '9B', '10A'],
    phone: '+1234567901',
    email: 'emily.d@school.com',
    avatar: 'https://bit.ly/prosper-baba',
    experience: '8 years',
  },
  {
    id: 4,
    name: 'Mr. Michael Brown',
    employeeId: 'TCH004',
    subject: 'Chemistry',
    classes: ['11B', '12A', '12B'],
    phone: '+1234567902',
    email: 'michael.b@school.com',
    avatar: 'https://bit.ly/kent-c-dodds',
    experience: '12 years',
  },
  {
    id: 5,
    name: 'Ms. Aisha Khan',
    employeeId: 'TCH005',
    subject: 'Biology',
    classes: ['10A', '10B'],
    phone: '+923001234567',
    email: 'aisha.k@school.com',
    avatar: 'https://bit.ly/prosper-baba',
    experience: '7 years',
  },
  {
    id: 6,
    name: 'Mr. Usman Tariq',
    employeeId: 'TCH006',
    subject: 'Computer Science',
    classes: ['10A', '9A', '9B'],
    phone: '+923008765432',
    email: 'usman.t@school.com',
    avatar: 'https://bit.ly/ryan-florence',
    experience: '6 years',
  },
  {
    id: 7,
    name: 'Ms. Noor Fatima',
    employeeId: 'TCH007',
    subject: 'Urdu',
    classes: ['10A'],
    phone: '+923111234567',
    email: 'noor.f@school.com',
    avatar: 'https://bit.ly/sage-adebayo',
    experience: '9 years',
  },
  {
    id: 8,
    name: 'Mr. Saad Ali',
    employeeId: 'TCH008',
    subject: 'Islamiat',
    classes: ['10A', '10B', '11A'],
    phone: '+923221112233',
    email: 'saad.a@school.com',
    avatar: 'https://bit.ly/dan-abramov',
    experience: '11 years',
  },
  {
    id: 9,
    name: 'Ms. Hina Shah',
    employeeId: 'TCH009',
    subject: 'Pakistan Studies',
    classes: ['10A', '10B'],
    phone: '+923331234567',
    email: 'hina.s@school.com',
    avatar: 'https://bit.ly/kent-c-dodds',
    experience: '5 years',
  },
];

// Mock Today's Classes (for Teacher)
export const mockTodayClasses = [
  {
    id: 1,
    time: '09:00 AM',
    subject: 'Mathematics',
    className: '10A',
    room: 'Room 201',
    topic: 'Calculus Introduction',
    studentCount: 32,
  },
  {
    id: 2,
    time: '10:00 AM',
    subject: 'Mathematics',
    className: '10B',
    room: 'Room 202',
    topic: 'Algebra Review',
    studentCount: 30,
  },
  {
    id: 3,
    time: '11:00 AM',
    subject: 'Mathematics',
    className: '11A',
    room: 'Room 301',
    topic: 'Trigonometry',
    studentCount: 28,
  },
  {
    id: 4,
    time: '02:00 PM',
    subject: 'Mathematics',
    className: '10A',
    room: 'Lab 101',
    topic: 'Practical Session',
    studentCount: 32,
  },
];

// Mock Assignments (for Students)
export const mockAssignments = [
  {
    id: 1,
    title: 'Mathematics Problem Set 5',
    subject: 'Mathematics',
    teacher: 'Dr. Sarah Wilson',
    dueDate: '2024-03-15',
    status: 'pending',
    points: 100,
    description: 'Complete problems 1-20 from Chapter 5',
  },
  {
    id: 2,
    title: 'Physics Lab Report',
    subject: 'Physics',
    teacher: 'Prof. James Anderson',
    dueDate: '2024-03-12',
    status: 'submitted',
    points: 50,
    description: 'Submit report on electricity experiment',
  },
  {
    id: 3,
    title: 'English Essay',
    subject: 'English',
    teacher: 'Ms. Emily Davis',
    dueDate: '2024-03-18',
    status: 'pending',
    points: 75,
    description: 'Write a 500-word essay on Shakespeare',
  },
  {
    id: 4,
    title: 'Chemistry Quiz',
    subject: 'Chemistry',
    teacher: 'Mr. Michael Brown',
    dueDate: '2024-03-10',
    status: 'graded',
    points: 25,
    score: 22,
    description: 'Online quiz on periodic table',
  },
];

// Mock Fee Data (Monthly Collection)
export const mockFeeData = [
  {
    month: 'Jan',
    collected: 850000,
    pending: 150000,
  },
  {
    month: 'Feb',
    collected: 920000,
    pending: 80000,
  },
  {
    month: 'Mar',
    collected: 780000,
    pending: 220000,
  },
  {
    month: 'Apr',
    collected: 950000,
    pending: 50000,
  },
  {
    month: 'May',
    collected: 890000,
    pending: 110000,
  },
  {
    month: 'Jun',
    collected: 970000,
    pending: 30000,
  },
];

// Mock Attendance Data (Last 7 Days)
export const mockAttendanceStats = [
  {
    day: 'Mon',
    present: 1180,
    absent: 70,
    late: 15,
    percentage: 94.4,
  },
  {
    day: 'Tue',
    present: 1195,
    absent: 55,
    late: 10,
    percentage: 95.6,
  },
  {
    day: 'Wed',
    present: 1150,
    absent: 100,
    late: 20,
    percentage: 92.0,
  },
  {
    day: 'Thu',
    present: 1175,
    absent: 75,
    late: 12,
    percentage: 94.0,
  },
  {
    day: 'Fri',
    present: 1200,
    absent: 50,
    late: 8,
    percentage: 96.0,
  },
  {
    day: 'Sat',
    present: 1100,
    absent: 150,
    late: 5,
    percentage: 88.0,
  },
  {
    day: 'Sun',
    present: 0,
    absent: 1250,
    late: 0,
    percentage: 0,
  },
];

// Mock Alerts
export const mockAlerts = [
  {
    id: 1,
    type: 'warning',
    title: 'Bus Delay',
    message: 'BUS-002 is running 10 minutes late due to traffic',
    time: '5 mins ago',
  },
  {
    id: 2,
    type: 'info',
    title: 'New Student Registration',
    message: '3 new students registered for Grade 10',
    time: '1 hour ago',
  },
  {
    id: 3,
    type: 'success',
    title: 'Fee Collection',
    message: '95% fees collected for this month',
    time: '2 hours ago',
  },
  {
    id: 4,
    type: 'error',
    title: 'RFID Scanner Issue',
    message: 'North Gate RFID scanner needs maintenance',
    time: '3 hours ago',
  },
];

// Mock Exam Results (for Students)
export const mockExamResults = [
  {
    id: 1,
    exam: 'Mid-Term Exam',
    date: '2024-02-15',
    subjects: [
      { name: 'Mathematics', score: 85, total: 100, grade: 'A' },
      { name: 'Physics', score: 78, total: 100, grade: 'B+' },
      { name: 'Chemistry', score: 92, total: 100, grade: 'A+' },
      { name: 'English', score: 88, total: 100, grade: 'A' },
    ],
    totalScore: 343,
    totalPossible: 400,
    percentage: 85.75,
    rank: 5,
  },
  {
    id: 2,
    exam: 'Unit Test 1',
    date: '2024-01-20',
    subjects: [
      { name: 'Mathematics', score: 45, total: 50, grade: 'A+' },
      { name: 'Physics', score: 42, total: 50, grade: 'A' },
      { name: 'Chemistry', score: 48, total: 50, grade: 'A+' },
      { name: 'English', score: 40, total: 50, grade: 'A' },
    ],
    totalScore: 175,
    totalPossible: 200,
    percentage: 87.5,
    rank: 3,
  },
];

// Mock Notifications
export const mockNotifications = [
  {
    id: 1,
    type: 'assignment',
    title: 'New Assignment Posted',
    message: 'Mathematics Problem Set 6 has been posted',
    time: '10 mins ago',
    read: false,
  },
  {
    id: 2,
    type: 'grade',
    title: 'Grade Posted',
    message: 'Your Chemistry Quiz has been graded',
    time: '1 hour ago',
    read: false,
  },
  {
    id: 3,
    type: 'attendance',
    title: 'Attendance Marked',
    message: 'Your attendance for today has been marked present',
    time: '3 hours ago',
    read: true,
  },
  {
    id: 4,
    type: 'fee',
    title: 'Fee Reminder',
    message: 'Your monthly fee is due in 3 days',
    time: '1 day ago',
    read: true,
  },
];

// Attendance records with detailed check-in/out data are now in mockAttendanceData.js
